[package]
name = "aide"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.32"
clap = { version = "4.4", features = ["derive"] }
fuzzy-matcher = "0.3"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
ratatui = "0.28"
crossterm = "0.27"
